### ISSUE TITLE
Hello,dear friend.I am a beginner who learn neo4j model and have a problem

### ISSUE THREAD

**Issue by ruigege66** [blockchain-etl/bitcoin-etl-airflow-neo4j#5]
Hello,dear friend.I am a beginner who learn neo4j model.I am from China and want to consult you about some thing which use ETL tools in neo4j.I have 100-400 million lines data which must transform  from mysql to neo4j,but I do not know how to transform quikly.See your repository about neo4j and you are an expert about it.So I expect your help,thank you!!

**Comment by tonicebrian** [comment]
Sorry but I cannot help at the moment.
